# Name of our action
name: Publish

# The event that will trigger the action
on:
  push:
    branches: [main]

# What the action will do
jobs:
  release:
    # The operating system it will run on
    runs-on: ubuntu-latest

    # The list of steps that the action will go through
    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          bun run release
